installed.packages('MASS')
library(MASS)
attach(Boston)
ls()
?Boston
nrow(Boston)
ncol(Boston)
summary(Boston)
boxplot(Boston$crim)
##I think rows signify town
summary(Boston$crim)

install.packages("ISLR")
library(ISLR)
data(Auto)
head(Auto)
names(Auto)
summary(Auto)
summary(Auto$mpg)
fivenum(Auto$mpg) 
boxplot(Auto$mpg)
hist(Auto$mpg)
summary(Auto$horsepower) 
summary(Auto$weight) 
fivenum(Auto$weight) 
 data_epi=read.csv(file.choose(),header=TRUE)
summary(data_epi$EPI)